# Generated by Django 4.1.1 on 2022-09-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useracc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vaccines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("description", models.CharField(max_length=1000, null=True)),
                ("date_for_administration", models.DateTimeField()),
            ],
        ),
    ]
