# Generated by Django 4.1.1 on 2022-09-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("useracc", "0002_vaccines"),
    ]

    operations = [
        migrations.RenameModel(old_name="Vaccines", new_name="Vaccine",),
    ]
