# Generated by Django 4.1.1 on 2022-09-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useracc", "0003_rename_vaccines_vaccine"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doctor",
                    models.CharField(
                        choices=[
                            ("dentist", "Dentist"),
                            ("children's doctor", "Children's doctor"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("date_reserved", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("checked", "Checked")],
                        max_length=200,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vaccine",
            name="status",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="vaccine",
            name="date_for_administration",
            field=models.DateTimeField(null=True),
        ),
    ]
