# Generated by Django 4.1.1 on 2022-09-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useracc", "0004_reservation_vaccine_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("checked", "Checked")],
                default="None",
                max_length=200,
                null=True,
            ),
        ),
    ]
