# Generated by Django 4.1.1 on 2022-09-30 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("useracc", "0006_alter_reservation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="child",
            field=models.CharField(default="None", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="vaccine",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="useracc.customer",
            ),
        ),
    ]
