# Generated by Django 4.1.1 on 2022-09-30 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("useracc", "0007_customer_child_vaccine_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="useracc.customer",
            ),
        ),
    ]
