# Generated by Django 4.1.1 on 2022-10-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useracc", "0014_alter_reservation_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="Id_number",
            field=models.IntegerField(null=True),
        ),
    ]
